### ISSUE TITLE
Some way to use this for drag and drop operations as well?

### ISSUE THREAD

**Issue by KillyMXI** [clowd/Clowd.Clipboard#2]
Natural integration with all UI frameworks is most likely not possible or will require individual wrappers, but it might still be nice to be able to reuse the same format handlers in some way.

Maybe an API that I can fill with required glue logic (callbacks to get present formats, get/set data for a format) and do the queries afterwards.
Or maybe provide more idiomatic extensions for IDataConverter so it could be used from the client code.

**Comment by caesay** [comment]
It is possible to create and use your own IDataConverter's. I have added some more overloads to make this easier in the latest update.
