### ISSUE TITLE
UniformResourceLocator/W and text/x-moz-url formats

### ISSUE THREAD

**Issue by KillyMXI** [clowd/Clowd.Clipboard#3]
I've seen UniformResourceLocatorW in the clipboard when copying an image from Edge browser, so I assume all Chromium-based browsers behave similarly.
Implementation should be the same as for FileName/W, except I don't think this one is obsolete.

I haven't checked whether `text/x-moz-url` can appear in the clipboard - I don't use Firefox. For now, it is mostly motivated by my interest in drag and drop operations (#2) and it is set by Edge there.

Implementation for `text/x-moz-url` is going to be a bit different. It includes a link and a title separated by a line break. The closest to the documentation I found from a brief look is there: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types#dragging_links

I can provide a PR for this one when I get time, if you're interested in contributions.
I find this package is pretty useful, especially considering clipboard support in Avalonia is missing some things at the moment.

**Comment by caesay** [comment]
> I can provide a PR for this one when I get time, if you're interested in contributions.
I find this package is pretty useful, especially considering clipboard support in Avalonia is missing some things at the moment.

I did start out wanting to make this library UI platform agnostic (with platform specific wrappers). Currently it's biased towards using WPF but even the bitmap parsing was written in a similar sort of way, so it should be possible to improve this library with native support for Avalonia etc.

Happy to accept improvements / suggestions and work with you to make this suitable for Avalonia use. You can join the [Clowd](https://github.com/clowd/Clowd) discord if you would like to discuss.

**Comment by caesay** [comment]
I have added UniformResourceLocatorW to the list of built-in formats, although you can use any format (even if it's not built-in) by using the `ClipboardFormat.CreateCustomFormat(string formatName)` method. Also, I have added platform specific libraries for `Avalonia` in this latest update.

**Comment by KillyMXI** [comment]
Awesome! Thank you very much.

Pretty good timing. I was pretty much done with my workarounds, but this morning I discovered transparency was lost in pasted images for some reason... While I was trying to figure out what might've happened, the package update came.
This cleaned my code quite a bit, and the issue is gone (My dodgy converters might be to blame).
So proper Avalonia images support is really came in handy.
