### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Seekeer** [clowd/Clowd.Clipboard#4]
Got code

                if(!string.IsNullOrEmpty(imagePath))
                {
                    var bitmap = new Bitmap(imagePath);

                    Clowd.Clipboard.ClipboardAvalonia.SetImage(bitmap);

                    builder.KeyDown(Keys.Control).SendKeys("v").KeyUp(Keys.Control).Build().Perform();
                }

                Clowd.Clipboard.ClipboardAvalonia.SetText(text);
                builder.KeyDown(Keys.Control).SendKeys("v").KeyUp(Keys.Control).Build().Perform();

It is working at first. But on second or N-th call I got System.NullReferenceException when trying to access `Clowd.Clipboard.ClipboardAvalonia`

**Comment by caesay** [comment]
Can you share the stacktrace please?

**Comment by Seekeer** [comment]
![image](https://user-images.githubusercontent.com/2019187/236599944-28aa7ca1-3f14-45d3-bb61-d581860143cb.png)

Your clipboard is using in class which is working with chromedriver to paste image and text in some input field.

        protected virtual void SendKeys(IWebElement input, string text, string imagePath)
        {
            try
            {
                if (string.IsNullOrEmpty(text))
                    return;

                input.Click();
                Actions builder = new Actions(driver);

                if (!string.IsNullOrEmpty(imagePath))
                {
                    var bitmap = new Bitmap(imagePath);
                    Clowd.Clipboard.ClipboardAvalonia.SetImage(bitmap);

                    builder.KeyDown(Keys.Control).SendKeys("v").KeyUp(Keys.Control).Build().Perform();
                }

                Clowd.Clipboard.ClipboardAvalonia.SetText(text);
                builder.KeyDown(Keys.Control).SendKeys("v").KeyUp(Keys.Control).Build().Perform();

            }
            catch (Exception ex)
            {

            }
        }

**Comment by caesay** [comment]
What's happening here is that the clipboard was unable to be opened - probably because some other process or thread had the clipboard open.

Can see here where we [try to call OpenClipboard](https://github.com/clowd/Clowd.Clipboard/blob/master/src/Clowd.Clipboard/ClipboardHandle.cs#L35) in a loop, if we are unable to open it within 1000ms then it will throw an exception. 

This is not a bug in Clowd.Clipboard, however I am going to leave this issue as that error/exeption message is incorrect and it should be a more helpful message.

**Comment by Seekeer** [comment]
> What's happening here is that the clipboard was unable to be opened - probably because some other process or thread had the clipboard open.
Strange. When Im using standart Avalonia Clipboard I dont have such problems. Any ideas where I could seek for reason?

**Comment by caesay** [comment]
I have improved the error handling
